apiVersion: kaptain.org/1.29
kind: docker-build-dockerfile
metadata:
  description: "Keelson base image - lean Debian Trixie slim with kubectl, yq 4, skopeo"

spec:
  layers:
    - ghcr.io/kube-kaptain/layer/layer-github-flow-strict:[1.4]
    - ghcr.io/kube-kaptain/layer/layer-image-environment-base:[1.3]
