name: Docker Build Dockerfile

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/docker-build-dockerfile.yaml@kube-manifest-packaging-and-distribution
    permissions:
      contents: write
      packages: write
    with:
      block-slashes: true
      block-conventional-commits: true
